### ISSUE TITLE
`plural` and `selectordinal`: allow single case `other`

### ISSUE THREAD

**Issue by OliverJAsh** [unsplash/intlc#108]
Some languages might only have one plural form.

E.g. cardinal. We send:

```
{day, selectordinal, one {#st} two {#nd>} few {#rd} other {#th}}
```

They return:

```
{day, selectordinal, other {#}}
```

E.g. ordinal. We send:

```
{numberOfPhotos, plural, one {# photos} two other {# photos}}
```

They return:

```
{numberOfPhotos, plural, other {# abc}}
```

Currently `intlc` throws if the only case is `other`:

```
dayWithOrdinal:1:22:
  |
1 | {day, selectordinal, other {#}}
  |                      ^^^^
unexpected "othe"
expecting "few", "many", "one", "two", "zero", '=', or white space
```

**Comment by samhh** [comment]
The counter-argument in terms of correctness is that this could be `{numberOfPhotos, number}`.

I see three options:

1. Leave it as-is, or ideally add a better parser error along the lines of "use the number type instead".
2. Allow no non-wildcard cases, but produce a warning. This'd add the notion of linting in some capacity. This may be useful for developers producing master messages whilst not blocking translators using suboptimal syntax.
3. Plainly allow no non-wildcard cases.

This also touches upon the broader question of whether and how we should favour correctness or acceptance (for want of a better word - think HTML in browsers). Vaguely related: #9, #27

**Comment by samhh** [comment]
One possible approach:

- Broadly try to make syntax as accepting as possible without sacrificing correctness.
- Introduce a `lint` subcommand that can lint against inefficient or otherwise suboptimal stuff like the above. This should be fairly straightforward analysis of the AST.
- Consider introducing a `format` subcommand which would in practice just rewrite spacing and ordering of interpolation tokens; think Prettier for our ICU messages. Probably blocked by #47.

The first point gives translators maximum flexibility. The latter two allow us to maintain correctness in our master translations.

**Comment by samhh** [comment]
What should we do if there are two `other` wildcard cases? I think that should still error as the translator's intent is unclear?

**Comment by OliverJAsh** [comment]
Yeah agreed!

**Comment by samhh** [comment]
#144 covered `select`. `plural` and `selectordinal` remain.
